apiVersion: v1
kind: Secret
metadata:
  name: infra-oauth2-secret
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-oauth2
    app.kubernetes.io/part-of: infra-platform
type: Opaque
stringData:
  spring.datasource.username: "<replace-me>"
  spring.datasource.password: "<replace-me>"
  spring.data.redis.password: "<replace-me>"
  infra.oauth2.clients.1.client-secret: "<replace-with-encoded-secret>"
  infra.oauth2.users.0.password: "<replace-with-encoded-password>"
  infra.oauth2.jwt.private-key: "<replace-with-private-key>"
