apiVersion: v1
kind: Service
metadata:
  name: infra-oauth2
  namespace: infra
  labels:
    app.kubernetes.io/name: infra-oauth2
    app.kubernetes.io/part-of: infra-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: infra-oauth2
  ports:
    - name: http
      port: 80
      targetPort: http
